# Ensure that PHP is installed in Travis' build environment. Travis provides several versions of
# PHP like 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, etc., each of them including XDebug and PHPUnit.
language: php

# Travis can cache content between builds. This speeds up the build process and saves resources.
cache:
  # With this option we can chose custom directories which should be cached between builds.
  directories:
    # Cache the directory where Symfony stores its slightly modified version of PHPUnit.
    - ./bin/.phpunit
    # Cache composer packages so "composer install" is faster.
    - $HOME/.composer/cache/files
    # Cache the Symfony binary so that it does not have to be reinstalled.
    - $HOME/.symfony

env:
  global:
    # Symfony's PHPUnit bridge provides a modified version of PHPUnit. The modified PHPUnit is
    # written to a directory that can be configured by the SYMFONY_PHPUNIT_DIR env var, or in
    # the same directory as the simple-phpunit if it is not provided. It's also possible to set
    # this env var in the phpunit.xml.dist file.
    - SYMFONY_PHPUNIT_DIR=./bin/.phpunit
    # Add the Symfony binary's path to PATH.
    - PATH="$HOME/.symfony/bin:$PATH"

# Defines all jobs which Travis will run in parallel. For each PHP version we support we will run one job.
matrix:
  # With fast finishing enabled, Travis CI will mark your build as finished as soon as one of two
  # conditions are met: The only remaining jobs are allowed to fail, or a job has already failed. In
  # these cases, the status of the build can already be determined, so there’s no need to wait around
  # until the other jobs finish.
  fast_finish: true
  include:
    - php: 7.4
    #- php: 8.0

before_install:
  # If it is available update the Symfony binary.
  - if symfony self:version; then symfony self:update ; fi
  # If it is not available install the Symfony binary.
  - if ! symfony self:version; then wget https://get.symfony.com/cli/installer -O - | bash ; fi

install:
  # Install Composer packages including dev dependencies listed in require-dev.
  - composer install
  # Install PHPUnit
  - ./bin/phpunit install
  # Copy the pre-built assets because we need them to run our functional PHPUnit tests.
  - cp -R tests/data/build/ public/
  # Create an empty .en.local file because our Makefile includes and therefore requires it.
  - touch .env.local

script:
  # There is no need to load data fixtures before running tests because the project repository
  # already includes a test database with all the fixtures needed to run the tests.
  - ./bin/phpunit
  # Check if composer.json is valid. To save time only do it during one of the jobs.
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || make lint-composer'
  # Check that the application doesn't use dependencies with known security vulnerabilities. To save time only do it during one of the jobs.
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || make dependencies-php-security-check'
  # Check that the PHP source code follows the project's syntax rules. To save time only do it during one of the jobs.
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || make cs-fixer-dry-run'
  # TODO: add psalm
  # Check that arguments injected into services match type declarations. To save time only do it during one of the jobs.
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || make lint-container'
  # Check that the YAML config files contain no syntax errors. To save time only do it during one of the jobs.
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || make lint-yaml'
  # Check that the Twig template files contain no syntax errors. To save time only do it during one of the jobs.
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || make lint-twig'
  # Checks that the XLIFF translations contain no syntax errors. To save time only do it during one of the jobs.
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || make lint-xliff'
  # Checks that Doctrine's mapping configurations are valid. To save time only do it during one of the jobs.
  - '[[ "$TRAVIS_PHP_VERSION" == "7.4" ]] || make lint-schema'
