controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '%supported_locales%'
    defaults:
        _locale: '%kernel.default_locale%'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
